---
baseurl: "https://hoas.top"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "hoas' blog | One Stupid Boy"
theme: "LoveIt"
metaDataFormat: "yaml"
algolia:
  index: "LoveIt"
  key: "d249e72c9ed9919b5b460f1d972ee0b7"
  appID: "51HIYUODXW"
---